on: [push]
name: build
jobs:
  runhaskell:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-${{ matrix.ghc }}-stack

      - uses: actions/setup-haskell@v1
        with:
          enable-stack: true

      - run: stack setup
      - run: stack build
      - run: stack test

  runhlint:
    name: Run HLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.ghc }}-stack

      - uses: actions/setup-haskell@v1
        with:
          enable-stack: true

      - run: stack setup
      - run: stack build
      - run: stack install hlint
      - run: stack exec hlint src
